### PR TITLE
fix: look for vault cached token before login

### PR DESCRIPTION
**Pull request by DaThumpingRabbit**
### Description
This commit adds the check of the cached vault token before doing the authentication flow over again

**Fixes:** <https://github.com/argoproj-labs/argocd-vault-plugin/issues/536>

### Checklist
Please make sure that your PR fulfills the following requirements:
- [x] Reviewed the guidelines for contributing to this repository
- [x] The commit message follows the [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] Tests for the changes have been updated
- [ ] Are you adding dependencies? If so, please run `go mod tidy -compat=1.17` to ensure only the minimum is pulled in.
- [ ] Docs have been added / updated
- [ ] Optional. My organization is added to USERS.md.

### Type of Change

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

### CODE REVIEW

**Comment by DaThumpingRabbit** [comment]
@werne2j @jkayani
Can you please run the workflow again ?
I have added tests on the use of cached tokens
Thanks !

**Comment by DaThumpingRabbit** [comment]
Hello @werne2j @jkayani 
Any news on this ? Can you please run the workflow ?
Thank you 😄

**Comment by werne2j** [comment]
@DaThumpingRabbit can you rebase your branch with main? Will run once up to date

**Comment by DaThumpingRabbit** [comment]
Ah yes sorry I didn't notice the updates on the main branch, I just rebased it

**Comment by DaThumpingRabbit** [comment]
Will you have a chance to review that ? I am waiting for this to reduce my vault lease consumption

**Comment by werne2j** [comment]
@DaThumpingRabbit thanks for the PR. Looking it over, I think the approach I would like to see taken is to move all the token stuff (checking for and setting token) from the individual vault auth files to the vault backend https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/backends/vault.go#L32. 

We then call the `v.AuthType.Authenticate` func if can’t find a token, we can change that func to return the token and then call the set token func with that token.

**Comment by DaThumpingRabbit** [comment]
I see, I started to do those changes, however, I think that the token storing part was delegated to the individual auth files because of the specific token use-case (where the vault client detects the variable itself)
Do you think I should still extract this part to the vault backend file and make an extra case for the token to be handled differently ?

**Comment by DaThumpingRabbit** [comment]
Or if this seems cleaner to you, we could add a method to the AuthType type to indicate whether the storing / retrieving of the token should be considered (maybe a ShouldStoreToken function that returns a boolean and the vault backend conditions its behavior according to that)

**Comment by DaThumpingRabbit** [comment]
@werne2j I just committed a proposition to remove duplicated code in the vault auth types as you mentioned by following the idea I posted above
Let me know if this isn't ok for you and I can revert this commit

**Comment by werne2j** [comment]
@DaThumpingRabbit Looking back over it, i think going with the first strategy is fine. No need to over think it. If you want to roll back to that commit we can kick off the CI and try to get this into the next release

**Comment by DaThumpingRabbit** [comment]
@werne2j Thanks for checking it, I just rolled back to the first solution as you said and I am ready on my side if you want to trigger the CI again and merge it !

**Review by werne2j — APPROVED** [review]
Thanks @DaThumpingRabbit

**Pull request merged**
