### PR TITLE
feat: allow selecting the secret namespace

### PR DESCRIPTION
**Pull request by blairdrummond**
### Description

Remove the hard-coded `Secrets("argocd")` for fetching the configuration secret, and instead default to the namespace of the service-account. This is with the aim of supporting this plugin with the [ArgoCD operator](https://argocd-operator.readthedocs.io/en/latest/) so that you can have this plugin on multiple argocd instances in one cluster (with different Vault roles)

**Relates to:** https://github.com/IBM/argocd-vault-plugin/issues/153

**Note: this basically assumes that either there is a mounted service account or the user explicitly names `-s argocd/vault-secret` in order to specify the secret namespace. That could be seen as a regression, but a fallback to "argocd" could easily be added.**

### CODE REVIEW

**Review by jkayani — COMMENTED** [review]
This change seems reasonable and I'm fine with the syntax change to specify a namespace and secret within. It _is_ a breaking change though, so we'll need to update the docs and I guess bump the major version. @werne2j any disagreement?

I also see we don't have any tests for the `-s` and `-c` options so I won't ask you to add any unless you'd like to. But we should probably do that at some point

**Review by jkayani — COMMENTED** [review]
>  but a fallback to "argocd" could easily be added

Maybe that's preferable to avoid the breaking change

**Comment by blairdrummond** [comment]
> > but a fallback to "argocd" could easily be added
> 
> Maybe that's preferable to avoid the breaking change

There is one *tiny* edgecase, where if they were previously using a service-account in another namespace (other than "argocd") but sourcing the secret from the argocd namespace, then the new default would be the service-account namespace instead of the previous behavior. So I think it would still be a breaking change, but it might break *less*

**Review by jkayani — COMMENTED** [review]
Current behavior: `argocd` namespace is used all the time with `--secret-name`

Desired behavior: Namespace of service account token is used unless a specific namespace is given - in a backwards compatible way

Maybe this should take a different form:

`--service-account-namespace` to tell AVP to read the secret from the namespace of the service account

`--secret-name` to tell AVP the name of the secret to read. Can be in the form `<string>/<string>` to specify a different namespace than `argocd`

Valid uses:

- `generate --secret-name vault/credentials`: reads `credentials` secret from `-n vault`
- `generate --service-account-namespace --secret-name credentials`: reads `credentials` from the namespace of the service account
- `generate --secret-name credentials`: reads `credentials` from `-n argocd`

Invalid uses:
- `generate --service-account-namespace`: no secret name given
- `generate --service-account-namespace --secret-name vault/credentials`: 2 different namespace options given

This way the current behavior is preserved in the 3rd valid use-case and you get the flexibility you need. It's a bit more work but I think it's preferable. Thoughts?

@werne2j In case you have a better idea

**Comment by blairdrummond** [comment]
@jkayani if you give a :+1: I can implement your proposal above. Let me know

**Comment by werne2j** [comment]
Going back to the original request..
> This is with the aim of supporting this plugin with the ArgoCD operator so that you can have this plugin on multiple argocd instances in one cluster (with different Vault roles)

This can be done today.. As we support plain environment variables. So your instance of Argo CD can use `envFrom` and whatever secret name you want. Then you dont have to pass the `-s` command to the generate command.

The alternative is we also support a config file. So you could mount a secret to a path and then pass the `-c` flag to the generate command. 

Maybe i am misunderstanding the request but you should be able to have multiple instance of the plugin in one cluster.

**Comment by blairdrummond** [comment]
Does the ArgoCD Operator currently support that? https://github.com/argoproj-labs/argocd-operator/issues/395 I don't know if that's in [the spec](https://github.com/argoproj-labs/argocd-operator/issues/395) yet

**Comment by werne2j** [comment]
@blairdrummond Ah right.. the operator. That has caused more than one problem with lack of supported features. My main focus is not to introduce any breaking changes. It seems that solution @jkayani suggested would provide the functionality you are looking for with no breaking changes. So i am on board with that feature.

**Comment by blairdrummond** [comment]
Ok sounds good, will implement the changes shortly

**Comment by blairdrummond** [comment]
@jkayani I've implemented your proposal for the `--service-account-namespace`. Let me know what you think!

**Comment by werne2j** [comment]
@blairdrummond Could you please add tests to cover the new lines aded?

**Review by jkayani — COMMENTED** [review]
Looks good, just want to see some tests for these flags.

It looks we handle the case of passing `--service-account-namespace` without `--secret-name` by just letting the plugin fail due to missing configuration, which is fine with me. All the other cases look to be handled properly.

**Comment by werne2j** [comment]
@blairdrummond are you still working on this pull request?

**Comment by blairdrummond** [comment]
@werne2j yes! Sorry, it hasn't been priority for us lately but will be soon (a few weeks). If you need it sooner I can find someone on our team to look at it

**Comment by werne2j** [comment]
No worries @blairdrummond was just checking before closing the PR. Appreciate your contibutions!

**Comment by werne2j** [comment]
Closing this in favor of https://github.com/argoproj-labs/argocd-vault-plugin/pull/251

**Pull request closed without merging**
