### PR TITLE
Restructure manifest for composability

### PR DESCRIPTION
**Pull request by jskrzypek**
- manifests: Restructure to allow BYO argocd
- manifests: Restore root manifest -> cmp-configmap

### Description
I've introduced 2 changes in separable commits, pasting the commit messages below.

These could be considered refactors but I think they're a bit more feature-y... YMMV.
Let me know If I should reword the commits.

> feat[manifests]: Allow BYO argocd
>
> Restructuring the manifests to allow consumers of AVP to bring their own argocd
> base by using the manifests under `manifests/plugin`.
>
> This allows consumers to integrate more easily with other CMPs or alternate
> versions of argo that the AVP maintainers haven't patched the manifests to
> include.
>
> Because the resources they patch are now not included in the kustomization bases
> in manifests/plugins, the standard `patchesStrategicMerge` strategy will fail.
> To fix this we switch to the `patches` interface and provide an explicit target
> for each patch.

And

> feat[manifests]: Restore root manifest
>
> PR #352 introduced the sidecar pattern, but also renamed the prior default
> manifest, which was available through a reference to
> https://github.com/argoproj-labs/argocd-vault-plugin//manifests
>
> To get the same app, consumers would need to change any exsting references to
> https://github.com/argoproj-labs/argocd-vault-plugin//manifests/cmp-configmap
>
> This commit introduces a simple proxy manifest that makes that change backwards
> compatible, meaning that now older references to
> https://github.com/argoproj-labs/argocd-vault-plugin//manifests
> will still resolve to the same app state as
> https://github.com/argoproj-labs/argocd-vault-plugin//manifests/cmp-configmap
> rather than just breaking.

**Fixes:** #369

### Checklist
Please make sure that your PR fulfills the following requirements:
- [x] Reviewed the guidelines for contributing to this repository
- [x] The commit message follows the [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] Tests for the changes have been updated
- [ ] Are you adding dependencies? If so, please run `go mod tidy -compat=1.17` to ensure only the minimum is pulled in.
- [x] Docs have been added / updated
- [ ] Optional. My organization is added to USERS.md.

### Type of Change

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

### CODE REVIEW

**Comment by jskrzypek** [comment]
Ok It does work now.

There's also another branch to look at here: https://github.com/argoproj-labs/argocd-vault-plugin/compare/main...jskrzypek:argocd-vault-plugin:jskrzypek/plugin-components

Which uses Kustomize Components, which are supposed to be more composable, instead of the base pattern

**Review by jkayani — COMMENTED** [review]
Use case makes sense to me and I'm fine with the approach as-is because it's clearly understandable. I'm not that worried about having broken backwards compatibility with the Kustomize app since I'd imagine most people are using a specific tag but I'm also not opposed to fixing it here as you've done. 

I think it'd be good to mention in the docs that these options are available (point to the `manifests/cmp-*/plugin` dir if you want to handle the Argo CD installation yourself, use our "opinionated" Kustomize app in `manifests/cmp-*` if you don't). Otherwise this PR is good with me!

**Comment by jskrzypek** [comment]
Great, I'll add a note to the docs tomorrow

**Comment by jskrzypek** [comment]
Hmmm @jkayani I was trying to consume this PR in our argocd kustomize app, and I'm finding that it actually may not work. 

I'm using this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v2.4.4
  - https://github.com/jskrzypek/argocd-vault-plugin//manifests/plugin/configmap?ref=jskrzypek/plugin-submanifests
```
But when I look at the argocd-repo-server, I don't see the initContainer that should be added by the manifest. 😞 

OTOH the Components strategy in my other branch does actually work when I do it this way:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v2.4.4

components:
  - https://github.com/jskrzypek/argocd-vault-plugin//manifests/components/sidecar?ref=jskrzypek/plugin-components
```

Can I ask you to double-check me on this? If you find the same, I'll just switch over the PR over to the components approach.

**Comment by jskrzypek** [comment]
Ok, yeah, after several tests, this just doesn't seem to work as intended. I'm going to close this PR and reopen based on the other branch.

**Comment by jskrzypek** [comment]
Closing in favor of #372

**Pull request closed without merging**
