### PR TITLE
Update useres.md

### PR DESCRIPTION
**Pull request by mariuslpop**
Thanks for all the great work!

# Description
Update users.md

### CODE REVIEW

**Review by jkayani — APPROVED** [review]
Thank you! FYI you'll have to sign the CLA for this PR to be merged I think (standard for all argoproj-labs projects I think)

**Comment by mariuslpop** [comment]
I understand. Sorry, I don't think I can do that without getting a review from legal first. I was hoping that since this is just a readme update the CLA wouldn't be required. Thanks again. I'll close the PR

**Comment by werne2j** [comment]
@mariuslpop If you’re ok with it, I will make the PR to add your company to the users list

**Comment by mariuslpop** [comment]
> @mariuslpop If you’re ok with it, I will make the PR to add your company to the users list

That's very kind of you. That sounds good to me. Thank you!

**Pull request closed without merging**
