### PR TITLE
Empty manifests should result in empty output

### PR DESCRIPTION
**Pull request by AlexanderProschek**
### Description
Removes the if statement to check if manifests are empty and updates the test accordingly

**Fixes:**
#363

### Checklist
Please make sure that your PR fulfills the following requirements:
- [x] Reviewed the guidelines for contributing to this repository
- [x] The commit message follows the [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x] Tests for the changes have been updated
- [x] Are you adding dependencies? If so, please run `go mod tidy -compat=1.17` to ensure only the minimum is pulled in.
- [x] Docs have been added / updated
- [x] Optional. My organization is added to USERS.md.

### Type of Change

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

### CODE REVIEW

**Comment by werne2j** [comment]
@AlexanderProschek Seems like a valid use case. Thanks for the contribution!

**Review by jkayani — COMMENTED** [review]
The "No manifests" error was introduced here: https://github.com/argoproj-labs/argocd-vault-plugin/pull/231. If we take this patch, doesn't that mean we'll have this issue again with the AVP integration with other tools, right?

**Comment by AlexanderProschek** [comment]
@jkayani if I understand correctly, what your change in #231 adds is the ability for AVP to act as a sort of guard against other programs mistakes and halt execution. By that same reasoning this should also fail:
```bash
~ ❯ ((>&2 echo "some error" && exit 1) | kubectl diff -f -); echo $?;
some error
0
```
which it does not. `kubectl` will happily take an empty yaml node.

My point (see #363) is that unlike AVP, other Kubernetes tools like `kubectl` and ArgoCD don't fail executing on an empty input, rather do exactly what the input tells them to do (empty in -> empty out). Convention requires errors to be handled before inputting things into a program.

May I suggest adding a debug flag that add some useful debugging info, including if the input is empty?

**Comment by jkayani** [comment]
Re-reading your issue and re-visiting the problem from the previous PR, I think you make a good case. At that time I'd also forgotten about `set -o pipefail` which would've solved the problem without any AVP code changes - I ran this test to confirm using the release of AVP before that previous PR was merged:

```
$ sh -c '((>&2 echo "some error" && exit 1) | avp_old generate -c ~/Documents/ops/argo/vault/ibm-sm-creds.yaml -); echo $?;'
some error
0

$ sh -c 'set -o pipefail; ((>&2 echo "some error" && exit 1) | avp_old generate -c ~/Documents/ops/argo/vault/ibm-sm-creds.yaml -); echo $?;'
some error
1

$ avp_old version
argocd-vault-plugin v1.5.0 (89e02217591d856e3902be247df36ec7d489270f) BuildDate: 2021-11-01T15:53:36Z
```

So given that `kubectl` and Argo CD are OK with empty manifests, you're right, I think we should be too. It'd also be good to remind users (like past me) about `-o pipefail` to help them debug situations via the docs. We do have the verbose mode introduced in #350 but it's no use unless it's explicitly enabled. If you wouldn't mind adding to the docs as part of this PR, I'm happy to accept this.

**Comment by AlexanderProschek** [comment]
@jkayani I added some docs in the howitworks README. Let me know if this is good or if you were looking for something else

**Review by jkayani — APPROVED** [review]

**Pull request merged**
